import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const lato = Lato({ subsets: ["latin"], weight:["300", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} flex md:gap-[58px] gap-4`}>
        <Sidebar />
        <div className="ml-20 mt-[47px] md:ml-[267px] text-white">{children}</div></body>
    </html>
  );
}
